<?php

namespace Hborras\TwitterAdsSDK\TwitterAds\Fields;

class FeatureFields
{
    const FEATURE_KEYS = 'feature_keys';

    const FEATURES = [
        'AGE_TARGETING',
        'ALLOW_SKIPPABLE_VIDEOS_FOR_VIDEO_VIEWS_PREROLL_OBJECTIVE',
        'AUCTION_INSIGHTS',
        'AWARENESS_OBJECTIVE',
        'BRAND_TPN',
        'CHARGE_FOR_GOOD_CLICK',
        'CONVERSATION_CARD',
        'CONVERSATION_CARD_FOUR_OPTIONS',
        'CONVERSATION_CARD_UNLOCK',
        'CPI_CHARGING',
        'DIRECT_MESSAGE_CARD',
        'DR_TAP',
        'ENGAGER_RETARGETING',
        'EVENT_TARGETING',
        'INSTALLED_APP_CATEGORY_TARGETING',
        'MOBILE_CONVERSION_TRANSACTION_VALUE',
        'OPTIMIZED_ACTION_BIDDING',
        'REACH_AND_FREQUENCY_ANALYTICS',
        'REACH_FREQUENCY_CAP',
        'VALIDATED_AGE_TARGETING',
        'VIDEO_VIEWS_MIDROLL_OBJECTIVE',
        'VIDEO_VIEWS_PREROLL_OBJECTIVE',
        'VIDEO_APP_DOWNLOAD_CARD'
    ];
}
